### ISSUE TITLE
Support string, bool, int simvar types 

### ISSUE THREAD

**Issue by LionheartUK** [patricksurry/pysimconnect#7]
Any Simconnect unit value marked as a "String" is not retreived by python (such as ATC ID)

Can this be fixed - or point me in the direction as to why they are not passed through.

**Comment by patricksurry** [comment]
Currently only numeric simvar types are supported.  I'll poke around to see what'd be involved for adding strings.

See https://github.com/patricksurry/pysimconnect/blob/master/simconnect/datadef.py#L35

**Comment by patricksurry** [comment]
Support for strings (=> python string) and enum/flag/mask (=> python int) added in v0.2.6
